### ISSUE TITLE
Long development

### ISSUE THREAD

**Issue by TheSainEyereg** [aoshax/Support#1]
You started developing your hack fucking **last summer**, when did it come?

**Comment by artemking4** [comment]
Technically, not an issue. 
I dont know when it will come, i have stuff to do in my life and i sometimes dont have enough time to develop the cheat. 
The cheat itself is mostly ready for the beta, but here comes another issue: the loader is not done. The backend is, but the loader currently has basically nothing but design. And also i need to properly setup the site, currently twentytwo is developing the main page for the site. Right now im on a small side project, so i will still not work on the cheat in a few days. When i will finish it, i will go and improve the doubletap, its implemented a bit improperly right now. You have to wait if you really want it. Developing a cheat with almost no free time (school, etc) is not very effective. Plus i sometimes lose the motivation to work on the project and i just take a short break, like now. 
Anyway, my holidays are beginning in a few days, so expect often updates in the next weeks.

**Comment by Eld3rly** [comment]
лох, когда аос?

**Comment by TheSainEyereg** [comment]
Проблема решена, мне сделали отсос
